### PR TITLE
fix '$\/]' in HTML::Entities::encode_entities

### LINKED ISSUE #44: encode_entities doesn't handle `$` (dollar sign) or `\/` (backslash, slash) as advertised
According to the documentation of `encode_entities`: https://metacpan.org/pod/HTML::Entities#encode_entities(-$string-)

> The unsafe characters is *[sic]* specified using the regular expression character class syntax (what you find within brackets in regular expressions).

However, it throws a bizarre error if you want to encode `$`:

```
$ perl -wE 'use HTML::Entities qw(encode_entities); say encode_entities q{$sin(x)$}, q{<&$}'
Unmatched [ in regex; marked by <-- HERE in m/([ <-- HERE <&5.040000)/ at (eval 1) line 1.
```

For comparison, if I use this exact string "within brackets in regular expressions", it works fine:
```
$ perl -wE 'my $unsafe_chars = q{<&$}; say q{$sin(x)$} =~ s{([$unsafe_chars])}{ sprintf "&#%d;", ord $1 }egr'
&#36;sin(x)&#36;
```

For now, I can work around the issue with a backslash before `$`, but I don't think this should be necessary:
```
$ perl -wE 'use HTML::Entities qw(encode_entities); say encode_entities q{$sin(x)$}, q{<&\$}'
&#36;sin(x)&#36;
```

---

Similarly, there are issues if you want to encode backslashes and slashes:
```
$ perl -wE 'use HTML::Entities qw(encode_entities); say encode_entities q{a/b\c/d}, q{<&\\\\/}'
Unmatched [ in regex; marked by <-- HERE in m/([ <-- HERE <&\\/ at (eval 1) line 1.
 while trying to turn range: "<&\\/"
 into code: sub {$_[0] =~ s/([<&\\/])/$char2entity{$1} || num_entity($1)/ge; }
  at /home/mauke/perl5/perlbrew/perls/perl-5.40.0/lib/site_perl/5.40.0/x86_64-linux-thread-multi-ld/HTML/Entities.pm line 454.
```
(There are 4 backslashes in the source code because (according to the rules for perl string literals) they represent 2 backslashes in the string, which (when interpreted as a regex) match one backslash literally.)

Again, the expected behavior using string interpolation in a character class:
```
$ perl -wE 'my $unsafe_chars = q{<&\\\\/}; say q{a/b\c/d} =~ s{([$unsafe_chars])}{ sprintf "&#%d;", ord $1 }egr'
a&#47;b&#92;c&#47;d
```

### PR DESCRIPTION
**Pull request by mauke**
encode_entities() generates and evals custom code at runtime (as a performance optimization). However, its code generation was too naive and certain characters could be used to break out of the character class regex:

 - `$` (dollar sign) would trigger perl's variable interpolation
 - `]` and `/` (the character class and regex delimiters, respectively)

The latter two were usually escaped, but not if they were preceded by `\` in the input, even if that `\` was itself escaped by another `\` (NB: this is why it is generally a mistake to handle escaping logic with look-behinds: you need arbitrary-width look-behind to figure out whether the current chain of backslashes is even or odd in length in order to know what is being escaped or not).

The latter issue was fixed by doing a single pass over the input string with no look-behind; the former by switching the delimiter to `'` (which inhibits interpolation).

Fixes #44.

### CODE REVIEW

**Comment by haarg** [comment]
I think it would be worth keeping parity with URI::Escape, which allows character classes like `[:alpha:]` to be used. That does not currently work, but it did in an earlier form of the code.

I fixed some similar issues in URI::Escape in libwww-perl/URI#112. It also eliminated the unneeded subref and string eval. I think I'd prefer to also fix that here as long as we're making changes. But the tests in this PR demonstrate a mistake in that PR. It doesn't properly account for all double `\\` sequences.

**Comment by mauke** [comment]
I've implemented support for POSIX-style character classes now, along with additional tests.

(The URI::Escape code doesn't seem to handle negated classes like `[[:^alpha:]]`.)

**Comment by haarg** [comment]
It would be good to also test escaping character classes like `\w`. Otherwise, lgtm.

**Comment by oalders** [comment]
@haarg this just needs additional tests?

**Comment by haarg** [comment]
I added some tests after merging.

**Comment by oalders** [comment]
Thanks, @mauke and @haarg!

**Comment by oalders** [comment]
Version 3.83 just released.

**Pull request merged**
